# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 570b4db5cf8ef2140df74dfe4eb8c5eb9223ee400007daad3f182c79b2f772c5eea45950fafc0ba9eec7368cb920da4e3eb17d1157d9eb55345365f0203ce1f5

test:
  secret_key_base: e4f742198d879b7b7c607a78b0584b29bb422625b04334510f859ef5e74debf82855bb6d540b1bfacfd65b40821ea602b583582c040bf3c0c1623a3088613270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
